name: agric_climatic
description: A Flutter app for predicting long-term agro-climatic data and analyzing sequential weather patterns.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.0.0
  provider: ^6.0.5
  fl_chart: ^0.65.0
  http: ^1.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^19.4.1
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
