// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLmAatnwcd0wlXtaUGuDXrJynxiUXkuoY',
    appId: '1:846124224235:web:472e20dbee673bd18938ae',
    messagingSenderId: '846124224235',
    projectId: 'agro-climatic',
    authDomain: 'agro-climatic.firebaseapp.com',
    storageBucket: 'agro-climatic.firebasestorage.app',
    measurementId: 'G-SWEY2P36BC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCldgKYVa9sPyhmsnOncVGh0R4HrLfrN7I',
    appId: '1:846124224235:android:37621ded5ef3b24c8938ae',
    messagingSenderId: '846124224235',
    projectId: 'agro-climatic',
    storageBucket: 'agro-climatic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvQvQvQvQvQvQvQvQvQvQvQvQvQvQvQvQ',
    appId: '1:123456789:ios:abcdef123456789',
    messagingSenderId: '123456789',
    projectId: 'agro-climatic',
    storageBucket: 'agro-climatic.appspot.com',
    iosBundleId: 'com.example.agricClimatic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvQvQvQvQvQvQvQvQvQvQvQvQvQvQvQvQ',
    appId: '1:123456789:ios:abcdef123456789',
    messagingSenderId: '123456789',
    projectId: 'agro-climatic',
    storageBucket: 'agro-climatic.appspot.com',
    iosBundleId: 'com.example.agricClimatic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvQvQvQvQvQvQvQvQvQvQvQvQvQvQvQvQ',
    appId: '1:123456789:web:abcdef123456789',
    messagingSenderId: '123456789',
    projectId: 'agro-climatic',
    authDomain: 'agro-climatic.firebaseapp.com',
    storageBucket: 'agro-climatic.appspot.com',
  );
}